name: spark
description: A learning tool for college outreach using BLE.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.10

  #facebook packages
#  flutter_facebook_login: ^3.0.0

  #google packages
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11

  cloud_firestore: ^0.13.4+2

  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.3.0

  rxdart: 0.20.0

  #animation packages
  rubber: ^0.4.0





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
